name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar el proyecto React
        run: npm run build

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with service account
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > ${HOME}/gcloud.json
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud.json"


      - name: Hacer deploy a Firebase Hosting
        run: firebase deploy --only hosting --project sce-appstore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
